### ISSUE TITLE
Edit API

### ISSUE THREAD

**Issue by olegsuv** [webexkievstudio/blacklist#10]
Get will send:
- url (string)
- phones (array)

Expecting: 
{"items":[{"comment":"TEST3?d","url":"http:\/\/olx.ua\/sd","phones":["380931112233","380931112277"]},{"comment":"TEST3?","url":"http:\/\/olx.ua\/s","phones":["380931112233"]}{"comment":"TEST3","url":"http:\/\/olx.ua\/","phones":["380931112233"]},{"comment":"TEST","url":"http:\/\/olx.ua\/","phones":["380931112233"]}],"success":true}

Set will send:
- url (string)
- phones (array)
- comment (string)

Expecting object with answer:
{"answer": "Item successully added", answerCode: "1", "success":true}
(or something like this)

Items which has duplications url && phones && comments should be merged

**Comment by ReenExe** [comment]
API change - can see in tests
Merge be better - to move in new issue.
