### ISSUE TITLE
Don't work search with array of phones

### ISSUE THREAD

**Issue by olegsuv** [webexkievstudio/blacklist#7]
Example of request: 
http://stlist.vergo.space/api/v1/estate/advertisement/search.json?phones%5B%5D=0660452368&phones%5B%5D=0938219958&url=http%3A%2F%2Folx.ua%2Fobyavlenie%2Fsdam-2-h-komn-na-olzhicha-dorogozhicha-18a-IDk1mZg.html%23eb870a3160%3Bpromoted&comment=

Expected: object with data

Received: {"error":{"code":500,"message":"Internal Server Error"}}

**Comment by ReenExe** [comment]
fix in develop version - will be soon in production
